fix: do venv activation in be local up, rather than preinit
IBM/lunchpail pull request #401
Opened 2024-10-09 06:34 UTC by aavarghese

2024-10-10 18:11 UTC, starpit approved these changes
lgtm

2024-10-11 15:39 UTC, starpit requested changes
squash commits, thanks!

2024-10-11 17:13 UTC, aavarghese reviewed
Sure - thanks Nick!!!

2024-10-11 17:19 UTC, starpit approved these changes
lgtm

2024-10-11 17:32 UTC, merged